if [ -f ~/.aliases ]; then
	. ~/.aliases
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

[[ -s "/home/mbargenq/.gvm/scripts/gvm" ]] && source "/home/mbargenq/.gvm/scripts/gvm"

# Powerline time
if [ -f `which powerline-daemon` ]; then
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  . /usr/share/powerline/bash/powerline.sh
fi
#source $HOME/pyenv3/lib/python3.7/site-packages/powerline/bindings/bash/powerline.sh

# bash history preservation
export HISTCONTROL=ignoredups:ignorespace
