# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# kube-ps1
function get_cluster_short() {
    echo "$1" | cut -d . -f1
}
KUBE_PS1_CLUSTER_FUNCTION=get_cluster_short
KUBE_PS1_BINARY=$HOME/bin/oc
if [[ -f $HOME/bin/kube-ps1.sh ]]; then
  source $HOME/bin/kube-ps1.sh
  PS1='[\u@\h \W $(kube_ps1)]\$ '
fi

# User specific environment and startup programs

GOPATH=$HOME/go
export GOPATH

PATH=$HOME/bin:$HOME/.local/bin:$GOPATH/bin:${PATH}
export PATH

function rebaseupstream () {
  branch=prod
  if ! [[ -z "$1" ]]; then
    branch=$1
  fi

  startbranch=$(git describe --contains --all HEAD)
  git checkout $branch
  git fetch upstream
  git fetch upstream --tags
  git rebase upstream/$branch
  git push origin $branch
  git push origin --tags
  git checkout ${startbranch}
}

# urg, gnome
unset SSH_ASKPASS

function set_ocm_token() {
  export OCM_TOKEN=`cat ~/.ocm.json | jq -r .access_token`
}
